version: '3.9'

services:
  db:
    environment:
      - POSTGRES_DB=cali_db
      - POSTGRES_USER=cali_adm
      - POSTGRES_PASSWORD=cali@123
    image: postgres
    ports:
      - '5432:5432'
    restart: always

  # api:
  #   build: .
  #   ports:
  #     - '3332:3332'
